# Generated by Django 5.1.6 on 2025-02-20 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0002_remove_dishes_author_remove_dishes_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='prepare_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 20, 15, 20, 12, 708848, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
