# Generated by Django 5.1.6 on 2025-02-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0005_rename_add_data_dishes_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='count',
            field=models.CharField(max_length=100),
        ),
    ]
