# Generated by Django 5.1.6 on 2025-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0003_dishes_prepare_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='prepare_time',
            field=models.IntegerField(),
        ),
    ]
