# Generated by Django 5.1.6 on 2025-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0006_alter_ingredients_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='preview',
            field=models.ImageField(default='photo/preview/2236228.png', upload_to='photo/preview/'),
        ),
    ]
