# Generated by Django 5.1.6 on 2025-02-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0007_alter_dishes_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.CharField(choices=[('Desert', 'Десерт'), ('Meat_dish', 'Мясные блюда'), ('Snacks', 'Закуски'), ('Soups', 'Супы'), ('Salads', 'Салаты')], default='Snack', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photo/dishes'),
        ),
    ]
